spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/test
    username: root
    password: 123456
#    url: mpw:drUrYiMDYdOp5e2sIDmIg7yjDt+u0O/vGkA7ri6pNY0=
#    username: mpw:A8/w4XVIJou2uNw3x1LXwg==
#    password: mpw:UxYizXwIfgpwgg6iFLYRkA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:      # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:     # 监控web
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filters: stat,wall   # 底层开启功能，stat（sql监控），wall（防火墙）
      filter:
        stat:     # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
      aop-patterns: com.xxml.admin.*  #监控SpringBean

  jdbc:
    template:
      query-timeout: 3

  redis:
    host: 0.0.0.0
    port: 6379
#    client-type: lettuce
#    lettuce:
#      pool:
#        max-active: 10
#        min-idle: 5

    client-type: jedis
    jedis:
      pool:
        max-active: 10

#  boot:
#    admin:
#      client:
#        url: http://localhost:8888
#        instance:
#          prefer-ip: false

  application:
    name: boot-admin


management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: info
    com.xxml: debug
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: enabled
      logic-delete-value: 0
      logic-not-delete-value: 1
      id-type: auto

mpw.key: 5a3fa229f6ca46c6